# Generated by Django 4.2.17 on 2025-01-12 22:26

from django.db import migrations

def link_owners_to_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            name = flat.owner,
            defaults ={
                'phonenumbers': flat.owners_phonenumber,
                'pure_phone' : flat.owner_pure_phone,
            }
        )
        owner.flat.set([flat])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20250113_0558'),
    ]

    operations = [
        migrations.RunPython(link_owners_to_flat),
    ]
