# Generated by Django 4.2.17 on 2025-01-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_remove_flat_owner_flat_owners_alter_owner_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
