# Generated by Django 4.2.17 on 2025-01-16 08:32

from django.db import migrations


def link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all().iterator():
        if flat.owners.exists():
            continue

        owner, created = Owner.objects.get_or_create(
            name='Неизвестный владелец',  
            defaults={
                'phonenumbers': 'Нет данных',  
                'pure_phone': None,  
            }
        )
       
        flat.owners.add(owner)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0023_remove_owner_flat_alter_complaint_flat_and_more'),
    ]

    operations = [
        migrations.RunPython(link_owners_to_flats),
    ]
