# Generated by Django 4.2.17 on 2025-01-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_alter_complaint_flat_alter_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(related_name='flat_owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
