# Generated by Django 4.2.17 on 2025-01-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_owner_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='properties', to='property.owner', verbose_name='Собственники'),
        ),
    ]
